var bible_data = {
	'创世记'		: {old:true , abbr:'创'  , count:50 },
	'出埃及记'		: {old:true , abbr:'出'  , count:40 },
	'利未记'		: {old:true , abbr:'利'  , count:27 },
	'民数记'		: {old:true , abbr:'民'  , count:36 },
	'申命记'		: {old:true , abbr:'申'  , count:34 },
	'约书亚记'		: {old:true , abbr:'书'  , count:24 },
	'士师记'		: {old:true , abbr:'士'  , count:21 },
	'路得记'		: {old:true , abbr:'得'  , count:4  },
	'撒母耳记上'	: {old:true , abbr:'撒上', count:31 },
	'撒母耳记下'	: {old:true , abbr:'撒下', count:24 },
	'列王纪上'		: {old:true , abbr:'王上', count:22 },
	'列王纪下'		: {old:true , abbr:'王下', count:25 },
	'历代志上'		: {old:true , abbr:'代上', count:29 },
	'历代志下'		: {old:true , abbr:'代下', count:36 },
	'以斯拉记'		: {old:true , abbr:'拉'  , count:10 },
	'尼希米记'		: {old:true , abbr:'尼'  , count:13 },
	'以斯帖记'		: {old:true , abbr:'斯'  , count:10 },
	'约伯记'		: {old:true , abbr:'伯'  , count:42 },
	'诗篇'			: {old:true , abbr:'诗'  , count:150},
	'箴言'			: {old:true , abbr:'箴'  , count:31 },
	'传道书'		: {old:true , abbr:'传'  , count:12 },
	'雅歌'			: {old:true , abbr:'歌'  , count:8  },
	'以赛亚书'		: {old:true , abbr:'赛'  , count:66 },
	'耶利米书'		: {old:true , abbr:'耶'  , count:52 },
	'耶利米哀歌'	: {old:true , abbr:'哀'  , count:5  },
	'以西结书'		: {old:true , abbr:'结'  , count:48 },
	'但以理书'		: {old:true , abbr:'但'  , count:12 },
	'何西阿书'		: {old:true , abbr:'何'  , count:14 },
	'约珥书'		: {old:true , abbr:'珥'  , count:3  },
	'阿摩司书'		: {old:true , abbr:'摩'  , count:9  },
	'俄巴底亚书'	: {old:true , abbr:'俄'  , count:1  },
	'约拿书'		: {old:true , abbr:'拿'  , count:4  },
	'弥迦书'		: {old:true , abbr:'弥'  , count:7  },
	'那鸿书'		: {old:true , abbr:'鸿'  , count:3  },
	'哈巴谷书'		: {old:true , abbr:'哈'  , count:3  },
	'西番雅书'		: {old:true , abbr:'番'  , count:3  },
	'哈该书'		: {old:true , abbr:'该'  , count:2  },
	'撒迦利亚书'	: {old:true , abbr:'亚'  , count:14 },
	'玛拉基书'		: {old:true , abbr:'玛'  , count:4  },
	'马太福音'		: {old:false, abbr:'太'  , count:28 },
	'马可福音'		: {old:false, abbr:'可'  , count:16 },
	'路加福音'		: {old:false, abbr:'路'  , count:24 },
	'约翰福音'		: {old:false, abbr:'约'  , count:21 },
	'使徒行传'		: {old:false, abbr:'徒'  , count:28 },
	'罗马书'		: {old:false, abbr:'罗'  , count:16 },
	'哥林多前书'	: {old:false, abbr:'林前', count:16 },
	'哥林多后书'	: {old:false, abbr:'林后', count:13 },
	'加拉太书'		: {old:false, abbr:'加'  , count:6  },
	'以弗所书'		: {old:false, abbr:'弗'  , count:6  },
	'腓立比书'		: {old:false, abbr:'腓'  , count:4  },
	'歌罗西书'		: {old:false, abbr:'西'  , count:4  },
	'帖撒罗尼迦前书': {old:false, abbr:'帖前', count:5  },
	'帖撒罗尼迦后书': {old:false, abbr:'帖后', count:3  },
	'提摩太前书'	: {old:false, abbr:'提前', count:6  },
	'提摩太后书'	: {old:false, abbr:'提后', count:4  },
	'提多书'		: {old:false, abbr:'多'  , count:3  },
	'腓利门书'		: {old:false, abbr:'门'  , count:1  },
	'希伯来书'		: {old:false, abbr:'来'  , count:13 },
	'雅各书'		: {old:false, abbr:'雅'  , count:5  },
	'彼得前书'		: {old:false, abbr:'彼前', count:5  },
	'彼得后书'		: {old:false, abbr:'彼后', count:3  },
	'约翰一书'		: {old:false, abbr:'约一', count:5  },
	'约翰二书'		: {old:false, abbr:'约二', count:1  },
	'约翰三书'		: {old:false, abbr:'约三', count:1  },
	'犹大书'		: {old:false, abbr:'犹'  , count:1  },
	'启示录'		: {old:false, abbr:'启'  , count:22 }
};
